### ISSUE TITLE
ng-class isOpen being duplicated

### ISSUE THREAD

**Issue by mindplace** [benmarch/angular-ui-tour#65] opened 2016-07-26 16:14 UTC
Hi, we're using your tour for our site, and a syntax error keeps popping up twice per tour step:

```
angular.js:13920 Error: [$parse:syntax] Syntax Error: Token '{' is an unexpected token at column 16 of the expression [{ in: isOpen } { in: isOpen() }] starting at [{ in: isOpen() }].
http://errors.angularjs.org/1.5.8/$parse/syntax?p0=%7B&p1=is%20an%20unexpected%20token&p2=16&p3=%7BNaNn%3A%isOpen%20%7D%20%7B%in%3A%isOpen()%20%7D&p4=%7B%in%3A%isOpen()%20%7D
    at http://docker:5000/bower_components/angular/angular.js:68:12
    at Object.throwError (http://docker:5000/bower_components/angular/angular.js:14555:11)
    at Object.ast (http://docker:5000/bower_components/angular/angular.js:14308:12)
    at Object.compile (http://docker:5000/bower_components/angular/angular.js:14771:31)
    at Parser.parse (http://docker:5000/bower_components/angular/angular.js:15700:29)
    at $parse (http://docker:5000/bower_components/angular/angular.js:15865:39)
    at Scope.$watch (http://docker:5000/bower_components/angular/angular.js:17104:19)
    at Object.link (http://docker:5000/bower_components/angular/angular.js:24929:15)
    at http://docker:5000/bower_components/angular/angular.js:1247:18
    at http://docker:5000/bower_components/angular/angular.js:9928:44
    at invokeLinkFn (http://docker:5000/bower_components/angular/angular.js:9934:9)
    at nodeLinkFn (http://docker:5000/bower_components/angular/angular.js:9335:11)
    at delayedNodeLinkFn (http://docker:5000/bower_components/angular/angular.js:9691:11)
    at compositeLinkFn (http://docker:5000/bower_components/angular/angular.js:8620:13)
    at publicLinkFn (http://docker:5000/bower_components/angular/angular.js:8500:30)
    at createTooltip (http://docker:5000/bower_components/angular-bootstrap/ui-bootstrap-tpls.js:4971:25)
```

When some tour step is on the page, here's what it looks like in the html:

<img width="467" alt="screen shot 2016-07-26 at 11 16 58 am" src="https://cloud.githubusercontent.com/assets/15573141/17145736/6f31411e-5329-11e6-87c6-e437546ab902.png">

So the issue is visible, but we don't understand why the `isOpen` is being duplicated, and why one is `isOpen` vs `isOpen()`, seems like only the second expression should be there based on your code:

```
angular.module('bm.uiTour').run(['$templateCache', function($templateCache) {
  $templateCache.put("tour-step-popup.html",
    "<div class=\"popover tour-step\"\n" +
    "     tooltip-animation-class=\"fade\"\n" +
    "     uib-tooltip-classes\n" +
    "     ng-class=\"{ in: isOpen() }\">\n" +
    "    <div class=\"arrow\"></div>\n" +
    "\n" +
    "    <div class=\"popover-inner tour-step-inner\">\n" +
    "        <h3 class=\"popover-title tour-step-title\" ng-bind=\"title\" ng-if=\"title\"></h3>\n" +
    "        <div class=\"popover-content tour-step-content\"\n" +
    "             uib-tooltip-template-transclude=\"originScope().tourStep.config('templateUrl') || 'tour-step-template.html'\"\n" +
    "             tooltip-template-transclude-scope=\"originScope()\"></div>\n" +
    "    </div>\n" +
    "</div>\n" +
    "");
```

Have you seen this issue before? Anything we can do here?

**Comment by benmarch** [comment] 2016-07-26 16:16
Hi @mindplace, I haven't noticed that before, it might be an update to Angular Bootstrap. What versions of AngularJS, Angular UI Bootstrap, and Angular UI Tour are you using?

**Comment by mindplace** [comment] 2016-07-26 16:32
Thanks @benmarch! Our versions: 

AngularJS: **1.5.0**
Angular deferred bootstrap: **0.1.9**
Angular UI Tour: **0.5.4**

**Comment by benmarch** [comment] 2016-07-26 16:45
Cool, what is the version of Angular UI Bootstrap (or angular-bootstrap) that you are using?

**Comment by mindplace** [comment] 2016-07-26 17:10
We're not actually using angular-bootstrap or requiring it anywhere.

**Comment by benmarch** [comment] 2016-07-26 17:27
Ah ok, so this library requires angular-bootstrap. Can you go into bower_components/angular-bootstrap and check the version in the bower.json manifest? If they updated it recently in a way that broke AUIT I should be able to fix it fairly quickly. I just want to make sure its not another issue. Can you also paste the entire bower manifest for your application here?

**Comment by mindplace** [comment] 2016-07-26 18:09
Sure, here's the contents of the bower.json file:

```
  "name": "marrymapp",
  "version": "0.0.1",
  "authors": [
    "Timothy Stephens <timothy.f.stephens@gmail.com>"
  ],
  "dependencies": {
    "angular": "~1.5.0",
    "angular-chart.js": "~0.7.3",
    "angular-dropdowns": "~1.1.0",
    "angular-sanitize": "~1.4.4",
    "Chart.js": "~1.0.2",
    "lodash": "~4.0.1",
    "moment": "~2.10.6",
    "oi.select": "~0.2.12",
    "ui-router": "~0.2.15",
    "angular-messages": "~1.4.8",
    "angular-animate": "~1.4.9",
    "angular-resource": "~1.4.9",
    "bluebird": "^3.3.5",
    "angular-ui-tour": "~0.5.4",
    "angular-deferred-bootstrap": "^0.1.9",
    "ui-router-extras": "^0.1.2"
  },
  "resolutions": {
    "angular": "~1.5.0"
  }
}
```

Should it require `angular-bootstrap` as a dependency?

**Comment by benmarch** [comment] 2016-07-26 18:27
Thanks @mindplace, nothing sticks out as a possible dependency clash to me (that's good). I am still going to need to know the version of angular-bootstrap that was pulled into your project. Even though you do not directly depend on it, it is pulled in as a transitive dependency because AUIT depends on it. If you go into `bower_components/angular-bootstrap/` and open up `bower.json` it will tell you the exact version number.

Thanks,
Ben

**Comment by mindplace** [comment] 2016-07-26 18:43
Hey @benmarch, sorry about that! Here's the contents of the bower.json file from `bower_components/angular-bootstrap/`:

```
{
    "author": {
        "name": "https://github.com/angular-ui/bootstrap/graphs/contributors"
    },
    "name": "angular-bootstrap",
    "keywords": [
        "angular",
        "angular-ui",
        "bootstrap"
    ],
    "license": "MIT",
    "ignore": [],
    "description": "Native AngularJS (Angular) directives for Bootstrap.",
    "version": "2.0.0",
    "main": ["./ui-bootstrap-tpls.js"],
    "dependencies": {
        "angular": ">=1.4.0"
    }
}
```

**Comment by megabyzus** [comment] 2016-07-26 20:28
We just downloaded this a few minutes ago (bower) and set it up. Albeit different from the OP, we are getting script link errors as well on initial load.

Our versions:
- angular.min.js (CDN)  1.5.6
- angular-ui-tour: 0.5.4
- angular-ui-bootstrap: 2.0.0

..amongst other related libs like ui-router and ngAnimate, etc.

We are getting the error below (BTW, URI's too large for errors.angularjs.org website so getting 414 error unrelated to this issue): 

> angular.js:38 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.6/$injector/modulerr?p0=credacious&p1=Error…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.6%2Fangular.min.js%3A36%3A486)

Any thoughts on general ETD on fixes?  Many thanks!

**Comment by benmarch** [comment] 2016-07-26 20:31
I can probably get to it tomorrow and if things go smoothly release tomorrow night or Thursday. Out of curiosity, does your build work if you use angular-ui-bootstrap 1.3.3?

**Comment by megabyzus** [comment] 2016-07-26 20:38
Unfortunately, it does not. 1.3.3 exhibits the similar error.

**Comment by benmarch** [comment] 2016-07-26 20:42
Ok, I think that might be a different issue. If you comment out the angular ui tour script tag do you still get the errors? I almost sounds like you might be pulling angular in twice (CDN and Bower)? I'm not sure if it is related to this library directly, it might be a transitive dependency. Without a full error message, it is difficult to diagnose. I will work on the angular ui 2.0 bug ASAP, but I am not sure it will fix the error that you are experiencing.

**Comment by megabyzus** [comment] 2016-07-26 21:00
Yes, app loads properly with the angular ui tour script tag (and bm.uiTour module) commented out.

**Comment by megabyzus** [comment] 2016-07-26 23:28
Hi, I was able to load 'clean' (I haven't tested anything to see what breaks). I ran the load process through the debugger and a module instantiations fail sequence is: 

bm.uiTour->ngSanitize->"Module 'ngSanitize' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument."

So something is requiring ngSanitize (I see it in the bower install folders but NOT in the instructions). So I added it via CDN (below--upgraded to AJS 1.5.8 BTW--unrelated)

`<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular-sanitize.min.js"></script>
`

Is there an issue or are the instructions simply missing this script reference?

I hope this helps.

Many thanks!

**Comment by benmarch** [comment] 2016-07-27 00:41
I am so sorry @megabyzus, you are correct, it is missing from the documentation. Thank you for debugging this for me, I will add it to the README right now. Again, I am very sorry for the confusion.

**Comment by megabyzus** [comment] 2016-07-27 00:49
This is a very useful tool and I'm happy to help.  Many thanks for your efforts.

**Comment by benmarch** [comment] 2016-07-27 00:52
I updated the README, and I made it programatic so that this won't happen again in the future :)

**Comment by benmarch** [comment] 2016-07-27 00:55
@mindplace, I was able to easily reproduce the issue while testing: https://travis-ci.org/benmarch/angular-ui-tour

I will have this fixed by tomorrow evening.

Thanks,
Ben

**Comment by megabyzus** [comment] 2016-07-27 12:56
@benmarch I think now another (the main one) item is missing in the doc:

<script src="js/angular-ui-tour/angular-ui-tour/dist/angular-ui-tour.min.js"></script>

**Comment by megabyzus** [comment] 2016-07-27 13:54
@benmarch I think now another (the main one) item is missing in the doc
`<script` src="js/external/angular-ui-tour/angular-ui-tour/dist/angular-ui-tour.min.js"></script>

**Comment by mindplace** [comment] 2016-07-27 14:22
hey @benmarch thank you so much for your help! I added `angular-bootstrap 1.3.3` to our dependencies and the syntax error is gone. Are you going to have `angular-ui-tour` explicitly require 1.3.3 in the future?

**Comment by benmarch** [comment] 2016-07-27 14:27
@megabyzus just fixed that, thank you for noticing!

@mindplace, my goal is to keep this working with as many versions of Angular Bootstrap as possible until I completely remove the dependency (which is currently a work in progress) so I will keep it as ">=0.14.3".

**Comment by benmarch** [comment] 2016-07-27 16:08
Ignore my last comment, I just looked through the source code for v2.0.0 and they made big changes. Since there is no easy way to determine the version of UIB programmatically at run time, I am going to lock in the allowed versions for now. I created #66 to fast-track the removal of the UIB dependency because I can't keep making adjustments every month to keep up with them. 

I released version 0.5.5 with the changes. Please let me know if that works for you, and feel free to close the ticket if it is working (or keep it open and comment if not).

**Comment by chillyistkult** [comment] 2016-08-09 14:38
I doesn't work and I would say if you have time you don't need to determine the UIB version programmatically, just adapt to the newest release (because thats what most people will use) and praise that they won't break backwards compatibility in the near future again. But thats more of a general problem when you depend on other libraries.

For the record we use UIB v2.0.1.

**Comment by benmarch** [comment] 2016-08-09 16:11
That's true, but based on my experience, and many of the issues raised, people tend not to upgrade their deps very frequently. Especially when it is a major release. I will continue to support 1.x for a little while, and work on either removing the dependency entirely, or finding a better way to integrate it.

**Comment by benmarch** [comment] 2016-08-16 21:24
Hey guys, sorry for the delay. I gave up on trying to remove Angular Bootstrap for now, so version 0.6.0 supports Angular Bootstrap 2.

**Closed by benmarch** 2016-08-16 21:24 UTC
