### ISSUE TITLE
Esc press closes my popup, when ui-tour-use-hotkeys="false". Backdrop stays active.

### ISSUE THREAD

**Issue by VladislavIvanov** [benmarch/angular-ui-tour#102] opened 2017-01-07 14:11 UTC
**I am using the _exact_ versions of the following libraries:**

* AngularJS: 1.5.8
* Angular Bootstrap: 2.0.0
* Angular UI Tour: 0.6.4

**I have installed this library via:** Bower

**I have observed the following behavior:** Esc press closes my popup, but backdrop is not closed. I don't use ui-tour-use-hotkeys="true".

**This is how I expected it to behave:** I want my popup to stay active.

**Here is my tour config, and all related step configs:**

```html
<body ui-tour></body>
```

```html
    <div id="welcome_step" tour-step-template-url="'app/modals/ui-tour/welcome-create-project-step.html'" tour-step-title="New Project" tour-step-orphan="true" tour-step-backdrop="true" tour-step-append-to-body="true" tour-step-animation="true" tour-step-placement="top" tour-step-popup-delay="1" tour-step tour-step-order="0"></div>
    <div id="configure_step" tour-step-template-url="'app/modals/ui-tour/configure-workflow-step.html'" tour-step-title="Configure your workflow" tour-step-orphan="true" tour-step-backdrop="true" tour-step-append-to-body="true" tour-step-animation="true" tour-step-placement="top" tour-step-popup-delay="1" tour-step tour-step-order="1"></div>
    <div id="wip_step" tour-step-template-url="'app/modals/ui-tour/wip-step.html'" tour-step-title="Work-in-progress" tour-step-orphan="true" tour-step-backdrop="true" tour-step-append-to-body="true" tour-step-animation="true" tour-step-placement="top" tour-step-popup-delay="1" tour-step tour-step-order="2"></div>
    <div id="addTasks_step" tour-step-template-url="'app/modals/ui-tour/create-tasks-step.html'" tour-step-title="Create tasks" tour-step-orphan="true" tour-step-backdrop="true" tour-step-append-to-body="true" tour-step-animation="true" tour-step-placement="top" tour-step-popup-delay="1" tour-step tour-step-order="3"></div>
    <div id="startTask_step" tour-step-template-url="'app/modals/ui-tour/start-task-step.html'" tour-step-title="Start with task" tour-step-orphan="true" tour-step-backdrop="true" tour-step-append-to-body="true" tour-step-animation="true" tour-step-placement="top" tour-step-popup-delay="1" tour-step tour-step-order="4"></div>
```

**Additional notes/code:**

**Comment by benmarch** [comment] 2017-01-09 15:27
Hey @VladislavIvanov, the escape key closing the popup appears to be a [UI Bootstrap feature](https://github.com/angular-ui/bootstrap/blob/master/src/tooltip/tooltip.js#L547). I can see about disabling it, or--at the very least--sync the backdrop with the popup.

**Comment by VladislavIvanov** [comment] 2017-01-09 16:47
Hey @benmarch, would you see about disabling it, will be great! 
Мeanwhile, what advice will you give me to avoid it? 
Thank you!

**Comment by benmarch** [comment] 2017-01-09 16:58
One thing you could do to avoid it (which is what i'll probably end up doing) is to add a keyup listener on the window when you start the tour, and if the keyCode is 27 then preventDefault(). Just make sure to remove the listener when the tour stops.

**Comment by VladislavIvanov** [comment] 2017-01-11 17:05
@benmarch I have tried preventDefault() on esc press, but still has the same problem. 
I keep trying to fix it. Thanks!

**Comment by benmarch** [comment] 2017-01-12 02:19
Hey @VladislavIvanov, I am unable to reproduce this issue. I created an orphan step with a backdrop and set hotkeys to false, but when I press ESC nothing happens at all. When I set hotkeys to true the tour ends. Do you have a public version of our app that I can use to debug? I wonder if it's another library that you are using, maybe you can dig into exactly what code is closing the popup.

**Comment by piotrimbierowicz** [comment] 2017-03-21 12:56
Works for me on angular bootstrap `2.0.0`-`2.0.2`, broken on `>2.1.0`

**Comment by benmarch** [comment] 2017-04-08 17:50
Hey @VladislavIvanov, not sure if this is working for you now, but please try with the latest version 0.8.0. Note that there are a few breaking changes that might need to be addressed: https://github.com/benmarch/angular-ui-tour#versions.

**Comment by benmarch** [comment] 2017-08-13 02:41
Closing issue. Please reopen if it is still present in the latest version.

**Closed by benmarch** 2017-08-13 02:41 UTC
