### ISSUE TITLE
Tour-Steps steel pointer events

### ISSUE THREAD

**Issue by dander401** [benmarch/angular-ui-tour#26] opened 2016-03-22 14:51 UTC
This issue has several work arounds, but its weird behavior. 

![screen shot 2016-03-22 at 10 36 46 am](https://cloud.githubusercontent.com/assets/4235673/13955194/2874f864-f01a-11e5-9c98-7265b2cbf95d.png)

I have a toolbar that has the shape of something like the following ascii art
```        
     __     
__|     |__
```
Theres a menu button to the right of the 'bump' that will always be clickable, and needs to be on the same-ish level to fit design. To fit this I have the parent toolbar have no pointer-events and the child has pointer events, The mouse will ignore the toolbar when the menu button is pressed. 

My problem is adding a tour-step around the toolbar eats the mouse events. I have tried ignoring the pointer events in the css
```css
tour-step{
    pointer-events: none;
}
```
but this does not work unless I also set the display property. Any value seems to work for it, but that means it effects the css of its children. 

I have never seen the pointer events fail, but then again, I've never tried to do it on an element without a display. I have tested this in Chrome and Firefox.

**Comment by benmarch** [comment] 2016-03-22 18:03
Hey @dander401, I don't exactly understand the issue. Is this a functional or stylistic problem that you are experiencing? What exactly is the expected behavior, and what are you observing when the tour step is added. Please include some markup/css/js. Thanks!

**Comment by dander401** [comment] 2016-03-22 18:07
functional
adding tour-step tags will capture click events even if they have it turned off via css

this becomes a problem if they wrap an element that needs to have a click through space.

**Comment by benmarch** [comment] 2016-03-22 18:10
The tour steps actually don't listen for any DOM events except the custom event that launches the tooltip. Does this happen only when the step is active or whenever you add the directive to the element?

**Comment by dander401** [comment] 2016-03-22 18:22
when i wrap a directive
``
<tour-step>
   <directiveWithOwnPrivateScope></directiveWithOwnPrivateScope>
</tour-step>

I guess capture is a bad choice of words... It is blocking the element beneath it from getting the click event.

Let me try to illustrate what is happening with some more ascii. 
T = tour step
d = directive 
x = trarget

html looks like this
```
<x></x>
<T>
   <d> </d>
</T>
```


So when i click over x this is what happens with my event
```
click -- d ---> T   x
         d      T
         d      T
         d      T
                T
```

I cannot get the tour-step to allow the click even through to the button behind it. 


...unrelated.... I got a whole new appreciation for monospaced fonts making that

**Comment by benmarch** [comment] 2016-03-22 18:29
Haha well it looks good, I see what you are trying to do. What happens if you wrap the directive with an element that does not have the tour step? I am trying to figure out why the tour step specifically would cause an issue like this. My suggestion would be to use a z-index to allow the target to reside in front of the directive, but that might not be possible if your UI prevents that. Can you try wrapping the directive with something other than a tour step and seeing if that makes a difference?

**Comment by dander401** [comment] 2016-03-22 18:32
what i did to get around it was just put the tour step on a div
```
<button></button>
<div tour-step>
  <directive></directive>
</div>

also I found adding a display property of block or inline-block to the tourstep would work... but that affected the children so I couldn't make a global css class for it

**Comment by dander401** [comment] 2016-03-22 18:34
I guess its worth noting that this is an easy thing to work around with a lot of options. But I spent awhile trying to do the clean css approach and looking up what I was doing wrong before succumbing to altering my html structure where I needed to

**Comment by benmarch** [comment] 2016-03-22 18:37
Ok, I'm just having a hard time understanding how it is directly related to the tour step. It seems like any element would result in the same behavior. Unless you tried putting the tour step on the directive without wrapping it, but it sounds like you want to wrap it.

**Comment by dander401** [comment] 2016-03-22 18:39
When I did this
```
<button></button>
<div tour-step>
  <directive></directive>
</div>
```
I was able to use css to set the pointer-events: none on the div to make this work.
The tour-step as an element would not respect the point-events property

**Comment by benmarch** [comment] 2016-03-22 18:43
Ah ok I understand... custom elements do behave differently, and I'm not sure if Angular uses the registerElement API. Did you try using a different custom element to see if that would work? Try wrapping it in `<myelement>...</myelement>` and styling it.

**Comment by dander401** [comment] 2016-03-22 18:49
good call, just created a stub element directive and did not work with the pointer events either unless I gave it a display property.

**Comment by benmarch** [comment] 2016-03-22 18:53
Right, and that is because custom elements do not have a default display property. Closing this issue as it is unrelated to this library.

**Closed by benmarch** 2016-03-22 18:53 UTC
