### ISSUE TITLE
Control the flow of the tour through controller

### ISSUE THREAD

**Issue by cesarcosta99** [benmarch/angular-ui-tour#19] opened 2016-03-17 16:35 UTC
Firstly, congratulations for the awesome library!

I'm trying to implement it on an AngularJS application and I'm not getting control the flow from a controller. I read the documentation but I didn't get it and I didn't find any demo or example.

Thanks!

**Comment by benmarch** [comment] 2016-03-17 16:49
Thanks, @cesarcosta99! 

I'm not sure I fully understand the question, but I think you are looking for an example of how to start/stop and navigate through the tour, right? There are a number of ways to control the flow, and all you need is a reference to the tour object. The easiest way is to look for it on the scope of the uiTour directive as `$scope.tour`, but you can also use the uiTourService and call `getTour()`. 

Take a look at the [demo here](http://benmarch.github.io/angular-ui-tour). Specifically, take a look at the Start Tour button's ngClick, and the TourDemoController within [angular-ui-tour-demo.js](https://github.com/benmarch/angular-ui-tour/blob/gh-pages/scripts/angular-ui-tour-demo.js). Once you have a reference to `tour` you can call `start()`, `next()`, `prev()`, `end()`, etc. on it.

If you can paste some code that isn't working I can take a look at that also. Let me know if this helps.

Thanks,
Ben

**Comment by cesarcosta99** [comment] 2016-03-17 17:09
Thanks a lot for answering so fast!

Let me try to explain better, I'm not so good in English... I'm trying to control the flow of the tour in another controller instead of TourDemoController, I took a look in the file and saw the functions there. I understood that I can use the **uiTourService** and call `getTour()`, I did that and got these errors:
In **Firefox**: _scope.originScope(...) is undefined_
In **Chrome**: _Cannot read property 'tourStep' of undefined_
I don't know if are errors or I'm doing something wrong.

Here's how i tried:
```javascript
function(uiTourService){
  window.setTimeout(function(){
    var tour = uiTourService.getTour();
    tour.start();
  }, 1000);
}
```

**Comment by benmarch** [comment] 2016-03-17 17:45
Hmm, I don't recommend using a timeout like that to wait for the tour to load. It is probably best to use the onReady function (see #1's answer). Also, make sure to have at least one tour step defined. Try something like this:

```html
<div ng-controller="MyController">
    <div ui-tour ui-tour-on-ready="onTourReady(tour)">
        <div tour-step tour-step-title="Welcome" tour-step-content="Hello World" tour-step-order="0"></div>
    </div>
</div>
```

```js
module.controller('MyController', function ($scope) {
    $scope.onTourReady = function (tour) {
        tour.start();
    } 
});
```

**Comment by cesarcosta99** [comment] 2016-03-17 19:02
@benmarch,
I did what you told and it worked, okay, but I'm getting the same error... I defined at least one step and print the directive tourStepPopup's scope in console and I realized the scope have the title, content and placement, but why the scope  is not receiving the `originScope()`?

Here's my HTML:
```html
<div ui-tour ui-tour-on-ready="onTourReady(tour)">
  <div tour-step tour-step-title="Menu" tour-step-content="This is menu options." tour-step-placement="right" data-ng-include="'tpl/blocks/aside.html'" class="app-aside">
  </div>
</div>
```

**Comment by benmarch** [comment] 2016-03-17 19:16
Hey @cesarcosta99, this might be caused by an issue that was introduced in 0.3.1. Please take a look at #20, I will have a fix for it later today. Sorry for the inconvenience, I'll fix it ASAP.

**Comment by cesarcosta99** [comment] 2016-03-17 19:23
No problem, @benmarch, thank you for the great job!

About my last comment: actually, when I run normally and print in console `tour.hasStep()`, it's comming false, but when I set a timeout it's comming with that error. I'll wait your fix, thanks!

**Comment by dander401** [comment] 2016-03-17 20:29
@cesarcosta99 @benmarch you can test to ensure that it is because of #20 by adding a few steps and seeing if some of them behave properly

**Comment by benmarch** [comment] 2016-03-17 21:27
Released 0.3.2, let's see if this issue persists.

**Comment by dander401** [comment] 2016-03-17 21:46
no change for me :(. still skipping steps

**Comment by cesarcosta99** [comment] 2016-03-17 21:52
I'll test as soon as I can!

**Comment by benmarch** [comment] 2016-03-18 02:36
@cesarcosta99 please test with 0.3.3, I did not release 0.3.2 properly so it is the same as 0.3.1. Thanks!

**Comment by cesarcosta99** [comment] 2016-03-18 12:21
@benmarch, didn't work for me :(

**Comment by benmarch** [comment] 2016-03-18 13:58
Ah ok, that was going to be my next suggestion. This requires AngularJS >= 1.3 and Angular UI Bootstrap > 0.14.3. Please let me know how it goes. Thanks!

**Comment by cesarcosta99** [comment] 2016-03-18 14:14
I made a few tests and and it's working fine right now, sorry for my mistake and thank you so much for the great support!

**Comment by benmarch** [comment] 2016-03-18 14:52
Awesome!! No problem at all :) Let me know if anything else comes up, or feel free to close the issue if everything works out.

**Comment by dander401** [comment] 2016-03-18 15:44
Ive got one more issue with a step not being added. 
I have an empty div that id like to put a tour step on but it doesnt seem to add. ( I generate the content for the div ). Do I need to just add and remove the tour step each time I change its content?

**Closed** 2016-03-18 16:55 UTC
