### ISSUE TITLE
ui-tour-template-url doesn't work

### ISSUE THREAD

**Issue by burakkilic** [benmarch/angular-ui-tour#52] opened 2016-05-07 11:11 UTC
Hi;

    scope.$eval(attrs[TourHelpers.getAttrName('templateUrl', 'uiTour')]); 

is undefined. My code is:

    ui-tour-template-url="myTooltipTemplate.html" and temaplate is:

        <script type="text/ng-template" id="myTooltipTemplate.html">
              <span>Special Tooltip with <strong>markup</strong> and {{ dynamicTooltipText }}</span>
        </script>

Where am I wrong?

**Comment by benmarch** [comment] 2016-05-07 16:07
Hey @burakkilic, myTooltipTemplate.html needs to be quoted. Please see @themainframe's answer to your other question (#50). Closing this issue as a duplicate of #50.

**Closed by benmarch** 2016-05-07 16:07 UTC
