### ISSUE TITLE
How can I block button clicks inside active step?

### ISSUE THREAD

**Issue by burakkilic** [benmarch/angular-ui-tour#53] opened 2016-05-10 13:27 UTC
Hello;

I am using backdrop function with the steps. I have some buttons inside divs. How can I block these buttons' click functions?

**Comment by benmarch** [comment] 2016-05-10 14:10
Hey @burakkilic, for something like that I would recommend just disabling the buttons while the tour is active. There are a few ways to determine if the tour is active, but the easiest might be adding `ui-tour-on-start` and `ui-tour-on-end` hooks that emit scope events that the button controller can listen for and disable/enable when they are heard. You can also get a reference to the tour in the button controller using `$scope.tour` (if there is no isolation) or `uiTourService.getTour()` (see docs) and listening on the tour object for start and end events. Note that if you listen on the tour, you _might_ need to call `$scope.$apply()`  (or [safe apply](https://coderwall.com/p/ngisma/safe-apply-in-angular-js)) after making a scope variable change. This library does not block buttons for you since many people desire that functionality to persist, and it can be done fairly easily using regular Angular mechanics and constructs.

**Comment by benmarch** [comment] 2016-05-30 22:38
Any update, @burakkilic?

**Comment by benmarch** [comment] 2016-08-17 19:16
Closing this as not a bug.

**Closed by benmarch** 2016-08-17 19:16 UTC
