### ISSUE TITLE
Type="button" missing from all buttons in the templateCache

### ISSUE THREAD

**Issue by kameelyan** [benmarch/angular-ui-tour#99] opened 2016-11-21 18:26 UTC
In the $templateCache for the tour-step-template.html, all the buttons are missing type="button", so this is giving unexpected results within other angular libraries. In my case, form validation is occurring whenever any of the buttons are pressed.

This can be fixed, by adding type="button" to all of the buttons.

**Comment by benmarch** [comment] 2016-11-21 18:27
Thanks, @kameelyan, I will add this to the next release.

**Comment by Weestdudochnicht** [comment] 2016-12-29 13:07
how long it will takes till the next release? i rly like to use the angular-ui-tour but i cant bec. of that problem

**Comment by benmarch** [comment] 2017-01-09 17:53
Very sorry for the delay, I have been traveling for the past 6 weeks... this will be in the next release, probably later this week or next weekend. In the meantime, you can make the change locally by copying the [tour-step-template.html](https://github.com/benmarch/angular-ui-tour/blob/master/app/templates/tour-step-template.html) into your project and adding the attribute there, then either use the `ui-tour-template-url` option or `$templateCache.put('tour-step-template.html', <template string>)` to override the default template.

**Closed** 2017-01-12 21:30 UTC

**Comment by Weestdudochnicht** [comment] 2017-01-13 10:06
Sorry, but your fix didn't solve my Problem. The ui-tour destroys my form validation. I'm using ng-form and got the following Error
angular.js:14199 TypeError: Cannot read property '$invalid' of undefined
    at validateForm (http://localhost:3000/components/generalFormValidation/formValidationService.js:34:16)
    at Scope.$scope.validateProspect (http://localhost:3000/prospects/modal/idCardCtrl.js:397:62)
    at fn (eval at compile (http://localhost:3000/plugins/angular/angular.js:15126:15), <anonymous>:4:239)
    at Scope.destination.(anonymous function) [as ngReallyClick] (http://localhost:3000/plugins/angular/angular.js:10279:22)
    at executeIfYes (http://localhost:3000/confirmModal/confirmModal.js:94:48)
    at processQueue (http://localhost:3000/plugins/angular/angular.js:16696:28)
    at http://localhost:3000/plugins/angular/angular.js:16712:27
    at Scope.$eval (http://localhost:3000/plugins/angular/angular.js:17994:28)
    at Scope.$digest (http://localhost:3000/plugins/angular/angular.js:17808:31)
    at Scope.$apply (http://localhost:3000/plugins/angular/angular.js:18102:24)(anonymous function) @ angular.js:14199(anonymous function) @ angular.js:10707processQueue @ angular.js:16704(anonymous function) @ angular.js:16712$eval @ angular.js:17994$digest @ angular.js:17808$apply @ angular.js:18102(anonymous function) @ angular.js:26597dispatch @ jquery.js:4435elemData.handle @ jquery.js:4121

That Error comes from the ng-form that will not be available when I'm using the tour.
Any Ideas? 
PS: Yes I did a correct Update to Version 0.7.0

**Comment by benmarch** [comment] 2017-01-13 19:45
Hey @Weestdudochnicht can you paste some code in here? Specifically the markup for the steps in the form and the relative methods in formValidationService.js and idCardCtrl.js.

**Comment by Weestdudochnicht** [comment] 2017-01-16 08:07
formValidationService.js:
 this.validateForm = function (form, requiredFields) {
        var formInvalid = false;
        var fieldsWithError = [];

        if(form.$invalid) { ......

prospectCtr.:
$scope.validateProspect = function () {
				var returnOfValidateProspectForm = formValidationService.validateForm($scope.myform, .....

html:
<div class="row prospects-modal modalNonScrollbox" ui-tour ui-tour-appendToBody="true" ui-tour-template-url="'/header/header-tour.html'" ui-tour-backdrop="false" ui-tour-on-ready="onTourReady(tour)">

    <ng-form name="myform" class="form-horizontal" role="form" novalidate>

.......
<div  tour-step tour-step-order="0" tour-step-title="{{'TOUR_PROSPECT_INFOCARD_STEP_ZERO_TITLE'|translate}}"  tour-step-content="{{'TOUR_PROSPECT_INFOCARD_STEP_ZERO_CONTENT'|translate}}" tour-step-placement="bottom"></div>

enough code or u need more. As i told u the cod worked without the tour. If i use the Tour, the tour work correct but the ng-form is broken

**Comment by benmarch** [comment] 2017-01-17 15:42
Based on the snippets, I can only assume that when you invoke validateForm from the template that your form is not on the scope you expect it to be on. Tour steps create an inherited scope on their targets, so be aware of how your DOM tree corresponds to your scope tree. This seems like a scope inheritance issue on your end; make sure you are not calling validateForm from the template _outside_ of the ngForm element. There might be another reason for the error, but without seeing all of the code, and knowing that `form` is undefined when you add a tour step, I can be fairly certain that this is what is going on.

**Comment by Weestdudochnicht** [comment] 2017-01-17 16:02
Okay. So my solution is now to put all TourElements outside a parentelement of any form. Seems to work. But that is no good solution bec. now i cant add a tourstep on an element.

**Comment by benmarch** [comment] 2017-01-17 16:25
Since that solution did work for you, the issue is that you are relying on scope inheritance (or lack thereof) to reference your form. You will experience the same issue if you place _any_ directive around your ngForm that creates a new scope (which is most of them) not just tour steps. My recommendation is to rearrange your DOM, or move your validation invocation to within the ngForm so that you know the form is available on that scope.
